#pragma once


float hash11(float p)
{
    vec2 p2 = fract(vec2(p * 5.3983, p * 5.4427));
    p2 += dot(p2.yx, p2.xy + vec2(21.5351, 14.3137));
    return fract(p2.x * p2.y * 95.4337);
}


//----------------------------------------------------------------------------------------
float hash12(vec2 p)
{
    p = fract(p * vec2(5.3983, 5.4427));
    p += dot(p.yx, p.xy + vec2(21.5351, 14.3137));
    return fract(p.x * p.y * 95.4337);
}


//----------------------------------------------------------------------------------------
float hash13(vec3 p)
{
    p = fract(p * vec3(5.3983, 5.4472, 6.9371));
    p += dot(p.yzx, p.xyz + vec3(21.5351, 14.3137, 15.3219));
    return fract(p.x * p.y * p.z * 95.4337);
}


//----------------------------------------------------------------------------------------
vec2 hash21(float p)
{
    vec2 p2 = fract(p * vec2(5.3983, 5.4427));
    p2 += dot(p2.yx, p2.xy +  vec2(21.5351, 14.3137));
    return fract(vec2(p2.x * p2.y * 95.4337, p2.x * p2.y * 97.597));
}


//----------------------------------------------------------------------------------------
vec2 hash22(vec2 p)
{
    p = fract(p * vec2(5.3983, 5.4427));
    p += dot(p.yx, p.xy +  vec2(21.5351, 14.3137));
    return fract(vec2(p.x * p.y * 95.4337, p.x * p.y * 97.597));
}


//----------------------------------------------------------------------------------------
vec3 hash31(float p)
{
    vec3 p2 = fract(p * vec3(5.3983, 5.4427, 6.9371));
    p2 += dot(p2.yzx, p2.xyz + vec3(21.5351, 14.3137, 15.3219));
    return fract(vec3(p2.x * p2.z * 95.4337, p2.x * p2.y * 97.597, p2.y * p2.z * 93.8365));
}


//----------------------------------------------------------------------------------------
vec3 hash32(vec2 p)
{
    p = fract(p * vec2(5.3983, 5.4427));
    p += dot(p.yx, p.xy +  vec2(21.5351, 14.3137));
    return fract(vec3(p.x * p.y * 95.4337, p.x * p.y * 97.597, p.x * p.y * 93.8365));
}


//----------------------------------------------------------------------------------------
vec3 hash33(vec3 p)
{
    p = fract(p * vec3(5.3983, 5.4427, 6.9371));
    p += dot(p.yzx, p.xyz  + vec3(21.5351, 14.3137, 15.3219));
    return fract(vec3(p.x * p.z * 95.4337, p.x * p.y * 97.597, p.y * p.z * 93.8365));
}

//----------------------------------------------------------------------------------------


#if 1
//Modified from: iq's "Integer Hash - III" (https://www.shadertoy.com/view/4tXyWN)
//Faster than "full" xxHash and good quality
uint baseHash(uvec2 p)
{
    p = 1103515245U * ((p >> 1U) ^ (p.yx));
    uint h32 = 1103515245U * ((p.x) ^ (p.y >> 3U));
    return h32 ^ (h32 >> 16);
}
#else
//XXHash32 based (https://github.com/Cyan4973/xxHash)
//Slower, higher quality
uint baseHash(uvec2 p)
{
    const uint PRIME32_2 = 2246822519U, PRIME32_3 = 3266489917U;
    const uint PRIME32_4 = 668265263U, PRIME32_5 = 374761393U;
    uint h32 = p.y + PRIME32_5 + p.x * PRIME32_3;
    h32 = PRIME32_4 * ((h32 << 17) | (h32 >> (32 - 17))); //Initial testing suggests this line could be omitted for extra perf
    h32 = PRIME32_2 * (h32 ^ (h32 >> 15));
    h32 = PRIME32_3 * (h32 ^ (h32 >> 13));
    return h32 ^ (h32 >> 16);
}
#endif

//---------------------2D input---------------------

float hash12(uvec2 x)
{
    uint n = baseHash(x);
    return float(n) * (1.0 / float(0xffffffffU));
}

vec2 hash22(uvec2 x)
{
    uint n = baseHash(x);
    uvec2 rz = uvec2(n, n * 48271U);
    return vec2((rz.xy >> 1) & uvec2(0x7fffffffU)) / float(0x7fffffff);
}

vec3 hash32(uvec2 x)
{
    uint n = baseHash(x);
    uvec3 rz = uvec3(n, n * 16807U, n * 48271U);
    return vec3((rz >> 1) & uvec3(0x7fffffffU)) / float(0x7fffffff);
}

vec4 hash42(uvec2 x)
{
    uint n = baseHash(x);
    uvec4 rz = uvec4(n, n * 16807U, n * 48271U, n * 69621U); //see: http://random.mat.sbg.ac.at/results/karl/server/node4.html
    return vec4((rz >> 1) & uvec4(0x7fffffffU)) / float(0x7fffffff);
}




uint whangHash(uint seed)
{
    seed = (seed ^ 61) ^ (seed >> 16);
    seed *= 9;
    seed = seed ^ (seed >> 4);
    seed *= 0x27d4eb2d;
    seed = seed ^ (seed >> 15);
    return seed;
}

float whangHashFloat(uint seed)
{
    seed = (seed ^ 61) ^ (seed >> 16);
    seed *= 9;
    seed = seed ^ (seed >> 4);
    seed *= 0x27d4eb2d;
    seed = seed ^ (seed >> 15);
    float value = float(seed) / (4294967296.0);

    return value;
}

// with more seeds, e.g use fragcoord.xy for v, s
// u for a sequential randoms
float whangHash(uint u, uint v, uint s)
{
    // https://www.reedbeta.com/blog/quick-and-easy-gpu-random-numbers-in-d3d11/
    // https://www.shadertoy.com/view/ldjczd
    uint seed = (u * 1664525u + v) + s;
    seed = (seed ^ 61u) ^ (seed >> 16u);
    seed *= 9u;
    seed = seed ^ (seed >> 4u);
    seed *= uint(0x27d4eb2d);
    seed = seed ^ (seed >> 15u);
    float value = float(seed) / (4294967296.0);
    return value;
}










// another hash without sine, 其他 hash 有问题的时候用这里的, 2025 2.27 遇到用前面 hash12 计算出来的 2d noise 出现 discontinuity, 但是 shadertoy 上没问题, 换成这里的 hash12 就好了
// Creative Commons Attribution-ShareAlike 4.0 International Public License
// Created by David Hoskins. May 2018

// The normalising multipler is 1.0 / (float)0xFFFFFFFF

// The labeling refers to the number of values - hash(out)(in)...
//---------------------------------------------------------------------------------------------------------------

#if 0
float hash11(uint q)
{
    uvec2 n = q * uvec2(1597334673U, 3812015801U);
    q = (n.x ^ n.y) * 1597334673U;
    return float(q) * 2.328306437080797e-10;
}

float hash11(float p)
{
    uvec2 n = uint(int(p)) * uvec2(1597334673U, 3812015801U);
    uint q = (n.x ^ n.y) * 1597334673U;
    return float(q) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
float hash12(uvec2 q)
{
    q *= uvec2(1597334673U, 3812015801U);
    uint n = (q.x ^ q.y) * 1597334673U;
    return float(n) / float(0xffffffffU);
}

float hash12(vec2 p)
{
    uvec2 q = uvec2(ivec2(p)) * uvec2(1597334673U, 3812015801U);
    uint n = (q.x ^ q.y) * 1597334673U;
    return float(n) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
float hash13(uvec3 q)
{
    q *= uvec3(1597334673U, 3812015801U, 2798796415U);
    uint n = (q.x ^ q.y ^ q.z) * 1597334673U;
    return float(n) * 2.328306437080797e-10;
}

float hash13(vec3 p)
{
    uvec3 q = uvec3(ivec3(p)) * uvec3(1597334673U, 3812015801U, 2798796415U);
    uint n = (q.x ^ q.y ^ q.z) * 1597334673U;
    return float(n) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
float hash14(uvec4 q)
{
    q *= uvec4(1597334673U, 3812015801U, 2798796415U, 1979697957U);
    uint n = (q.x ^ q.y ^ q.z ^ q.w) * 1597334673U;
    return float(n) * 2.328306437080797e-10;
}

float hash14(vec4 p)
{
    uvec4 q = uvec4(ivec4(p)) * uvec4(1597334673U, 3812015801U, 2798796415U, 1979697957U);
    uint n = (q.x ^ q.y ^ q.z ^ q.w) * 1597334673U;
    return float(n) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
vec2 hash21(uint q)
{
    uvec2 n = q * uvec2(1597334673U, 3812015801U);
    n = (n.x ^ n.y) * uvec2(1597334673U, 3812015801U);
    return vec2(n) * 2.328306437080797e-10;
}

vec2 hash21(float p)
{
    uvec2 n = uint(int(p)) * uvec2(1597334673U, 3812015801U);
    n = (n.x ^ n.y) * uvec2(1597334673U, 3812015801U);
    return vec2(n) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
vec2 hash22(uvec2 q)
{
    q *= uvec2(1597334673U, 3812015801U);
    q = (q.x ^ q.y) * uvec2(1597334673U, 3812015801U);
    return vec2(q) * 2.328306437080797e-10;
}

vec2 hash22(vec2 p)
{
    uvec2 q = uvec2(ivec2(p)) * uvec2(1597334673U, 3812015801U);
    q = (q.x ^ q.y) * uvec2(1597334673U, 3812015801U);
    return vec2(q) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
vec2 hash23(uvec3 q)
{
    q *= uvec3(1597334673U, 3812015801U, 2798796415U);
    uvec2 n = (q.x ^ q.y ^ q.z) * uvec2(1597334673U, 3812015801U);
    return vec2(n) * 2.328306437080797e-10;
}

vec2 hash23(vec3 p)
{
    uvec3 q = uvec3(ivec3(p)) * uvec3(1597334673U, 3812015801U, 2798796415U);
    uvec2 n = (q.x ^ q.y ^ q.z) * uvec2(1597334673U, 3812015801U);

    return vec2(n) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
vec3 hash31(uint q)
{
    uvec3 n = q * uvec3(1597334673U, 3812015801U, 2798796415U);
    n = (n.x ^ n.y ^ n.z) * uvec3(1597334673U, 3812015801U, 2798796415U);
    return vec3(n) * 2.328306437080797e-10;
}
vec3 hash31(float p)
{

    uvec3 n = uint(int(p)) * uvec3(1597334673U, 3812015801U, 2798796415U);
    n = (n.x ^ n.y ^ n.z) * uvec3(1597334673U, 3812015801U, 2798796415U);
    return vec3(n) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
vec3 hash32(uvec2 q)
{
    uvec3 n = q.xyx * uvec3(1597334673U, 3812015801U, 2798796415U);
    n = (n.x ^ n.y ^ n.z) * uvec3(1597334673U, 3812015801U, 2798796415U);
    return vec3(n) * 2.328306437080797e-10;
}

vec3 hash32(vec2 q)
{
    uvec3 n = uvec3(ivec3(q.xyx)) * uvec3(1597334673U, 3812015801U, 2798796415U);
    n = (n.x ^ n.y ^ n.z) * uvec3(1597334673U, 3812015801U, 2798796415U);
    return vec3(n) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
vec3 hash33(uvec3 q)
{
    q *= uvec3(1597334673U, 3812015801U, 2798796415U);
    q = (q.x ^ q.y ^ q.z) * uvec3(1597334673U, 3812015801U, 2798796415U);
    return vec3(q) * 2.328306437080797e-10;
}

vec3 hash33(vec3 p)
{
    uvec3 q = uvec3(ivec3(p)) * uvec3(1597334673U, 3812015801U, 2798796415U);
    q = (q.x ^ q.y ^ q.z) * uvec3(1597334673U, 3812015801U, 2798796415U);
    return vec3(q) * 2.328306437080797e-10;
}

//---------------------------------------------------------------------------------------------------------------
vec4 hash44(uvec4 q)
{
    q *= uvec4(1597334673U, 3812015801U, 2798796415U, 1979697957U);
    q = (q.x ^ q.y ^ q.z ^ q.w) * uvec4(1597334673U, 3812015801U, 2798796415U, 1979697957U);
    return vec4(q) * 2.328306437080797e-10;
}

vec3 hash44(vec4 p)
{
    uvec4 q = uvec4(ivec4(p)) * uvec4(1597334673U, 3812015801U, 2798796415U, 1979697957U);
    q = (q.x ^ q.y ^ q.z ^ q.w) * uvec4(1597334673U, 3812015801U, 2798796415U, 1979697957U);
    return vec3(q) * 2.328306437080797e-10;
}



#endif
